-- 코드를 입력하세요
SELECT TO_NUMBER(TO_CHAR(DATETIME,'HH24')) AS HOUR, COUNT(*) COUNT
FROM ANIMAL_OUTS
GROUP BY TO_CHAR(DATETIME,'HH24') 
HAVING TO_CHAR(DATETIME,'HH24') >= 9
AND TO_CHAR(DATETIME,'HH24') <= 19
ORDER BY HOUR
